frontend/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

frontend/app/main/views.py
import json
from . import main
from ..api.ProductClient import ProductClient
from ..api.UserClient import UserClient
from ..api.OrderClient import OrderClient
from ..api.ShoppingCartClient import ShoppingCartClient
from flask import jsonify, render_template, session, redirect, url_for, flash, request
from flask_login import current_user, login_required

def isLogin():
    if 'user' not in session:
        return False
    return True

def getBrand():
    brands = ProductClient.get_brands()
    brandList = []
    for b in brands:
        brandList.append(b)
    return brandList

def getSPC():
    spc = ShoppingCartClient.get_spc()
    if spc['message'] != False:
        spc = spc['result']
        return spc
    else:
        return spc

@main.route('/')
def home():
    products = ProductClient.get_products()
    productList = []
    for p in products:
        productList.append(p)
    if isLogin() == False:
        return render_template('main/home.html', productList=productList, brandList=getBrand())
    return render_template('main/home.html', productList=productList, brandList=getBrand(), shoppingcart=getSPC())

@main.route('/profile')
def profile():
    if isLogin() == False:
        flash('Bạn chưa đăng nhập', 'danger')
        return redirect(url_for('auth.login'))
    info = session['user']
    return render_template('main/profile.html', info=info, shoppingcart=getSPC())

@main.route('/getproudctsbybrand/<int:brand_id>')
def get_products_by_brand(brand_id):
    products = ProductClient.get_products_by_brand(brand_id)
    productList = []
    for p in products:
        productList.append(p)
    if isLogin() == False:
        return render_template('main/home.html', productList=productList, brandList=getBrand())
    else:
        return render_template('main/home.html', productList=productList, brandList=getBrand(), shoppingcart=getSPC())

@main.route('/getproudctsbykeyword', methods=['GET', 'POST'])
def get_products_by_keyword():
    keyword = request.form['search']
    products = ProductClient.get_products_by_keyword(keyword)
    productList = []
    for p in products:
        productList.append(p)
    if isLogin() == False:
        return render_template('main/home.html', productList=productList, brandList=getBrand())
    else:
        return render_template('main/home.html', productList=productList, brandList=getBrand(), shoppingcart=getSPC())

@main.route('/product/detail/<int:product_id>')
def get_product_detail(product_id):
    product = ProductClient.get_product(product_id)
    products = ProductClient.get_products_by_brand(product['brand_id'])
    productList = []
    for p in products:
        productList.append(p)
    if isLogin() == False:
        return render_template('main/product_detail.html', product=product, productList=productList, brandList=getBrand())
    else:
        return render_template('main/product_detail.html', product=product, productList=productList, brandList=getBrand(), shoppingcart=getSPC())

@main.route('/addtocart')
def add_to_cart():
    if isLogin():
        product_id = request.args.get('id')
        result = ShoppingCartClient.add_to_cart(product_id)
        quantity = result['result']['quantity']
        return jsonify({'msg': True, 'count': quantity})
    else:
        flash('Bạn chưa đăng nhập', 'danger')
        return redirect(url_for('auth.login'))

@main.route('/shoppingcart')
def shoppingcart():
    if isLogin():
        spc = ShoppingCartClient.get_cart_items()
        if spc['message'] != False:
            itemList = []
            for item in spc['result']:
                itemList.append(item)
            return render_template('main/shoppingcart.html', itemList=itemList, brandList=getBrand(), shoppingcart=getSPC())
        else:
            return render_template('main/shoppingcart.html', brandList=getBrand(), shoppingcart=getSPC())
    else:
        flash('Bạn chưa đăng nhập', 'danger')
        return redirect(url_for('auth.login'))

@main.route('/shoppingcart/delete/<int:item_id>', methods=['GET'])
def deleteItem(item_id):
    ShoppingCartClient.delete_cart_item(item_id)
    return redirect(url_for('main.shoppingcart'))

@main.route('/orderinfo', methods=['GET', 'POST'])
def orderInfo():
    if isLogin():
        item_selected = []
        total = 0
        for id in request.form.getlist('item'):
            item = ShoppingCartClient.get_cart_item(id)
            item_selected.append(item)
            total += item['final_price']
        session['total'] = total
        address = UserClient.get_address()
        info = session['user']
        return render_template('main/order.html', brandList=getBrand(), shoppingcart=getSPC(), itemList=item_selected, total=total, address=address, info=info)
    else:
        flash('Bạn chưa đăng nhập', 'danger')
        return redirect(url_for('auth.login'))

@main.route('/order', methods=['POST'])
def order():
    city = request.form.get('city')
    district = request.form.get('district')
    ward = request.form.get('ward')
    road = request.form.get('road')
    total = session.get('total')
    exist = UserClient.does_exist_address(city, district, ward, road)
    if exist['result'] == False:
        address = UserClient.add_address(city, district, ward, road)
        address_id = address['id']
    else:
        address_id = exist['address']['id']
    order = OrderClient.add_order(address_id, total)
    order_id = order['id']
    for (product_id, quantity) in zip(request.form.getlist('product_id'), request.form.getlist('quantity')):
        OrderClient.add_order_item(order_id, product_id, quantity)
    for item_id in request.form.getlist('item_id'):
        ShoppingCartClient.delete_cart_item(item_id)
    return redirect(url_for('main.history'))

@main.route('/history')
def history():
    if isLogin():
        orderList = []
        orders = OrderClient.get_orders()
        for order in orders:
            orderList.append(order)
        return render_template('main/history.html', brandList=getBrand(), shoppingcart=getSPC(), orderList=orderList)
    else:
        flash('Bạn chưa đăng nhập', 'danger')
        return redirect(url_for('auth.login'))

@main.route('/history/orderdetail/<int:order_id>')
def orderDetail(order_id):
    if isLogin():
        order_items = OrderClient.get_order_items(order_id)
        itemList = []
        total = 0
        for item in order_items:
            itemList.append(item)
            total += item['final_price']
        return render_template('main/order_detail.html', brandList=getBrand(), shoppingcart=getSPC(), itemList=itemList, total=total)
    else:
        flash('Bạn chưa đăng nhập', 'danger')
        return redirect(url_for('auth.login'))

frontend/app/templates/main/history.html
{% extends "base.html" %}

{% block page_content %}
<div class="container-xl">
	<div class="table-responsive">
		<div class="table-wrapper">
			<div class="table-title">
				<div class="row">
					<div class="col-sm-6">
						<h2><b>Lịch sử mua hàng</b></h2>
					</div>
				</div>
			</div>
			<table class="table table-striped table-hover">
				<thead>
					<tr>
                        <th>Mã đơn hàng</th>
                        <th>Ngày</th>
                        <th>Tổng giá trị</th>
                        <th>Trạng thái</th>
						<th>Địa chỉ</th>
                        <th>Thao tác</th>
					</tr>
				</thead>
				<tbody>
					{% for order in orderList %}
					<tr>
                        <td>{{ order.id }}</td>
                        <td>{{ order.created_at }}</td>
						<td>{{ order.total | conv_curr }}</td>
						<td>{{ order.status }}</td>
						<td>{{order.address.road}}, {{order.address.ward}}, {{order.address.district}}, {{order.address.city}}</td>
                        <td>
							<a href="/history/orderdetail/{{ order.id }}">Xem</a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

frontend/app/templates/main/home.html
{% extends "base.html" %}

{% block page_content %}
<div class="container mydiv">
    <div class="row">
        {% for product in productList %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <img src="{{ url_for('static', filename='images/'+ product.image) }}" alt="{{ product.name }}" class="card-img-top">
                <div class="card-body">
                  <a href="/product/detail/{{product.id}}" class="" class="card-title">{{product.name}}</a>
                  <p style="color: red"><strike>{{product.price | conv_curr}}</strike></p>
                  <h5 style="color: green">{{(product.price - (product.price * product.discount)/100)  | conv_curr}}</h5>
                  <button class="btn btn-primary addToCart" data-id="{{product.id}}">Thêm vào giỏ hàng</button>
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

frontend/app/templates/main/order.html
{% extends "base.html" %}

{% block page_content %}
<div class="container-xl">
    <form action="{{ url_for('main.order') }}" method="post">
        <div class="modal-body">
            <h5>Thông tin khách hàng</h5>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Tên khách hàng</label>
                        <input type="text" class="form-control" name="name" value="{{ info.fullname }}" onkeydown="return false;" required>
                    </div>
                    <div class="form-group">
                        <label>Số điện thoại</label>
                        <input type="text" class="form-control" name="phone" value="{{ info.phone_number }}" onkeydown="return false;" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Địa chỉ Email</label>
                        <input type="email" class="form-control" name="name" value="{{ info.email }}" onkeydown="return false;" required>
                    </div>
                </div>
            </div>
            <hr>
            <h5>Địa chỉ giao hàng</h5>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Thành phố</label>
                        <input type="text" class="form-control" name="city" value="{{ address.city }}" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Quận</label>
                        <input type="text" class="form-control" name="district" value="{{ address.district }}" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Phường</label>
                        <input type="text" class="form-control" name="ward" value="{{ address.ward }}" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Số nhà + đường</label>
                        <input type="text" class="form-control" name="road" value="{{ address.road }}" required>
                    </div>
                </div>
            </div>
            <hr>
            <h5>Danh sách mặt hàng</h5>
            <div class="table-responsive">
                <div class="table-wrapper">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Tên sản phẩm</th>
                                <th>Giá</th>
                                <th>Số lượng</th>
                                <th>Tổng</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in itemList %}
                            <tr>
                                <input type="hidden" value="{{item.item_id}}" name="item_id">
                                <input type="hidden" value="{{item.product_id}}" name="product_id">
                                <input type="hidden" value="{{item.quantity}}" name="quantity">
                                <td></td>
                                <td>{{ item.name }}</td>
                                <td>
                                    <strike>{{ item.price | conv_curr }}</strike>
                                    <br>
                                    {{(item.price - (item.price*item.discount)/100) | conv_curr }}

                                </td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.final_price | conv_curr }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-md-9"></div>
                        <div class="col-md-3"><b>Tổng tiền cần trả: {{ total | conv_curr }}</b></div>
                    </div>
                </div>
        </div>
        </div>
        <div class="modal-footer">
            <input type="submit" class="btn btn-success" value="Đặt hàng">
        </div>
    </form>
</div>
{% endblock %}

frontend/app/templates/main/order_detail.html
{% extends "base.html" %}

{% block page_content %}
<div class="container-xl">
	<div class="table-responsive">
		<div class="table-wrapper">
			<div class="table-title">
				<div class="row">
					<div class="col-sm-6">
						<h2><b>Thông tin đơn hàng</b></h2>
					</div>
				</div>
			</div>
			<table class="table table-striped table-hover">
				<thead>
					<tr>
                        <th></th>
                        <th>Tên sản phẩm</th>
                        <th>Giá</th>
                        <th>Số lượng</th>
						<th>Tổng</th>
					</tr>
				</thead>
				<tbody>
					{% for item in itemList %}
					<tr>
                        <td></td>
                        <td>{{ item.name }}</td>
						<td>
                            <strike>{{ item.price | conv_curr }}</strike>
                            <br>
                            {{(item.price - (item.price*item.discount)/100) | conv_curr }}

                        </td>
                        <td>{{ item.quantity }}</td>
						<td>{{ ((item.price - (item.price*item.discount)/100) * item.quantity) | conv_curr }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
			<div class="row">
				<div class="col-md-9"></div>
				<div class="col-md-3"><b>Tổng giá trị: {{ total | conv_curr }}</b></div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

frontend/app/templates/main/product_detail.html
{% extends "base.html" %}

{% block page_content %}
<div class="row">
    <div class='col-md-5'>
        <img src="{{ url_for('static', filename='images/'+ product.image) }}" alt="{{ product.name }}" class="card-img-top">
    </div>
    <div class='col-md-7'>
        <h3>{{product.name}}</h3>
        <h5 style="color: red"><strike>{{product.price | conv_curr}}</strike></h5>
        <h4 style="color: green">{{(product.price - (product.price * product.discount)/100)  | conv_curr}}</h4>
        <p><b>Số lượng còn: {{product.stock}} chiếc</b></p>
        <p>{{product.desc}}</p>
        <button class="btn btn-primary addToCart" data-id="{{product.id}}">Thêm vào giỏ hàng</button>
    </div>
</div>
<br>
<br>
<hr>
<div class="row">
    <h3>Các sản phẩm cùng thương hiệu</h3>
    <div class="container mydiv">
        <div class="row">
            {% for product in productList %}
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ url_for('static', filename='images/'+ product.image) }}" alt="{{ product.name }}" class="card-img-top">
                    <div class="card-body">
                      <a href="/product/detail/{{product.id}}" class="" class="card-title">{{product.name}}</a>
                      <p style="color: red"><strike>{{product.price | conv_curr}}</strike></p>
                      <h5 style="color: green">{{(product.price - (product.price * product.discount)/100)  | conv_curr}}</h5>
                      <button class="btn btn-primary addToCart" data-id="{{product.id}}">Thêm vào giỏ hàng</button>
                    </div>
                  </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

frontend/app/templates/main/profile.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-xl-6 col-md-12">
                <div class="card user-card-full">
                    <div class="row m-l-0 m-r-0">
                        <div class="col-sm-4 bg-c-lite-green user-profile">
                            <div class="card-block text-center text-white">
                                <div class="m-b-25">
                                    <img src="https://img.icons8.com/bubbles/100/000000/user.png" class="img-radius"
                                        alt="User-Profile-Image">
                                </div>
                                <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="card-block">
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Thông tin</h3>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <p class="m-b-10 f-w-600">Họ và tên</p>
                                        <h6 class="text-muted f-w-400">{{ info.fullname }}</h6>
                                    </div>
                                    <div class="col-sm-12">
                                        <p class="m-b-10 f-w-600">Username</p>
                                        <h6 class="text-muted f-w-400">{{ info.username }}</h6>
                                    </div>
                                    <div class="col-sm-12">
                                        <p class="m-b-10 f-w-600">Email</p>
                                        <h6 class="text-muted f-w-400">{{ info.email }}</h6>
                                    </div>
                                    <div class="col-sm-12">
                                        <p class="m-b-10 f-w-600">Số điện thoại</p>
                                        <h6 class="text-muted f-w-400">{{ info.phone_number }}</h6>
                                    </div>
                                    <div class="col-sm-12">
                                        <p class="m-b-10 f-w-600"></p>
                                        <a href="{{url_for('auth.edit_user')}}">Chỉnh sửa thông tin cá nhân</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

frontend/app/templates/main/shoppingcart.html
{% extends "base.html" %}

{% block page_content %}
<div class="container-xl">
	<form action="{{ url_for('main.orderInfo') }}" method="post">
	<div class="table-responsive">
		<div class="table-wrapper">
			<div class="table-title">
				<div class="row">
					<div class="col-sm-6">
						<h2><b>Giỏ hàng</b></h2>
					</div>
					<div class="col-sm-6">
						<button class="btn btn-success" value="Đặt hàng">Đặt hàng</button>
					</div>
				</div>
			</div>
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th>
							<span class="custom-checkbox">
								<input type="checkbox" id="selectAll">
								<label for="selectAll"></label>
							</span>
						</th>
                        <th>Tên sản phẩm</th>
                        <th>Giá</th>
                        <th>Số lượng</th>
						<th>Tổng</th>
						<th>Thao tác</th>
					</tr>
				</thead>
				<tbody>
					{% for item in itemList %}
					<tr>
						<td>
							<span class="custom-checkbox">
								<input type="checkbox" id="select" name="item" value="{{ item.item_id }}">
								<label for="selectOne"></label>
							</span>
						</td>
                        <td>{{ item.name }}</td>
						<td>
                            <strike>{{ item.price | conv_curr }}</strike>
                            <br>
                            {{(item.price - (item.price*item.discount)/100) | conv_curr }}

                        </td>
                        <td>{{ item.quantity }}</td>
						<td>{{ ((item.price - (item.price*item.discount)/100) * item.quantity) | conv_curr }}</td>
						<td>
							<a href="/shoppingcart/delete/{{ item.item_id }}" class="delete"><i class="material-icons" title="Delete">&#xE872;</i></a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
	</form>
</div>
<script>
	$(document).ready(function(){
		var checkbox = $('table tbody input[type="checkbox"]');
		$("#selectAll").click(function(){
		if(this.checked){
			checkbox.each(function(){
			this.checked = true;
			});
		} else{
			checkbox.each(function(){
			this.checked = false;
			});
		}
		});
		checkbox.click(function(){
		if(!this.checked){
			$("#selectAll").prop("checked", false);
		}
		});
	});
</script>
{% endblock %}